### ISSUE TITLE
Project states it is GPL but license notices are missing from source files

### ISSUE THREAD

**Issue by joachimmetz** [msuhanov/dfir_ntfs#2]
Project states it is GPL but license notices are missing from source files

See https://www.gnu.org/licenses/gpl-howto.en.html on how to use the GPL

E.g. the start of https://github.com/msuhanov/dfir_ntfs/blob/master/ntfs_parser should contain:
```
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
```

**Comment by msuhanov** [comment]
This is not required by the "TERMS AND CONDITIONS" section of the GNU GPLv3.

The "How to Apply These Terms to Your New Programs" section of the GNU GPLv3 is a recommendation, because there is no way the license is void if this recommendation isn't followed by the author.

[According to the FSF FAQ](https://www.gnu.org/licenses/gpl-faq.en.html#NoticeInSourceFile), _this has nothing to do with the specifics of the GNU GPL_. Also, the "TERMS AND CONDITIONS" section of the GNU GPLv3 mentions a situation when a program doesn't use the notices described in the "How to Apply These Terms to Your New Programs" section: "_If the Program does not specify a version number of the GNU General Public License, you may choose any version ever published by the Free Software Foundation_" (this has no direct connection to the current issue, but this clearly shows that the absence of the recommended notices, which always include the license version to be used, is allowed by the FSF).

Besides, the notices you mentioned can't be used, because the GNU GPLv3 is used, not the GNU GPLv3+.

**Comment by joachimmetz** [comment]
> This is not required by the "TERMS AND CONDITIONS" section of the GNU GPLv3.

I opt to add it, deviating for default practices adds more confusion then benefit.

```
The purpose of a free software license is to give certain rights to all users of a program. If it is not clear what rights you have given them, that defeats the purpose. Our practices are designed to avoid any uncertainty.
```

> Besides, the notices you mentioned can't be used, because the GNU GPLv3 is used, not the GNU GPLv3+.

It is unclear what you mean, to me "any later version" reads as GPLv3+

```
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.
```

**Comment by msuhanov** [comment]
> It is unclear what you mean, to me "any later version" reads as GPLv3+

This project is using the version 3 only (but not any later version).

**Comment by joachimmetz** [comment]
Ack I think this is covered under the section `14. Revised Versions of this License.` of the license, but you can always remove `, or (at your option) any later version.` from the license notice. As indicated this is for sake of clarity primarily.

**Comment by msuhanov** [comment]
There is no legal reason to do so. There is no practical reason to do so.

**Comment by joachimmetz** [comment]
The practical reason is as indicated by me and many other source are "less confusion a more clear message", but this up to you. Know that without this specific clarity there are people that cannot contribute or use your code.

https://opensource.stackexchange.com/questions/6813/is-using-the-gplv3-without-putting-a-license-notice-in-each-source-file-ok

**Comment by msuhanov** [comment]
> Know that without this specific clarity there are people that cannot contribute or use your code.

People may have any reason not to contribute, it's totally up to them to decide whether to contribute or not (e.g., some people don't contribute to GPL projects at all). The missing boilerplate notices don't create an issue of legal and/or practical nature.
